
Vagrant.configure("2") do |config|
 
  config.vm.box = "vechugres-centos8"

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 81, host: 8081

  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant"

  config.vm.provision "shell", inline: <<-SHELL

	sudo mkdir -p /var/www/static/html
	sudo chmod -R 0755 /var/www/static/html
	sudo mkdir -p /var/www/dynamic/html
	sudo chmod -R 0755 /var/www/dynamic/html
	sudo cp /vagrant/index.html /var/www/static/html
	sudo cp /vagrant/index.php /var/www/dynamic/html
  	sudo mkdir /etc/httpd/sites-available
	sudo mkdir /etc/httpd/sites-enabled
	sudo cp /vagrant/static.conf /etc/httpd/sites-available/
	sudo cp /vagrant/dynamic.conf /etc/httpd/sites-available/
	sudo cp /vagrant/httpd.conf /etc/httpd/conf/
  	sudo chcon -R --type=httpd_sys_rw_content_t /var/www/dynamic/html
	sudo ln -s /etc/httpd/sites-available/static.conf /etc/httpd/sites-enabled/static.conf
	sudo ln -s /etc/httpd/sites-available/dynamic.conf /etc/httpd/sites-enabled/dynamic.conf
	
	sudo systemctl restart httpd

  SHELL

end
