
Vagrant.configure("2") do |config|

  config.vm.box = "vechugres/centos8"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "vagrant.vm"
  end

  config.ssh.insert_key = false

  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 81, host: 8081, host_ip: "127.0.0.1"

  config.vm.synced_folder ".", "/vagrant"

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
