---
- name: setup nexus
  hosts: localhost
  become: yes
  pre_tasks:
   - apt:
      pkg:
       - gpg
      state: present
   - apt_key:
      url: https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public

   - apt_repository:
      repo: deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ buster main
      state: present
      update_cache: true

   - name: Install Java
     apt:
      name: adoptopenjdk-8-hotspot
      state: present

  vars:
    jenkins_ip: localhost
    nexus_ip: localhost
    staging_ip: localhost
    production_ip: localhost
    jenkins_user: admin
    jenkins_password: admin
    nexus_user_uploader: uploader
    nexus_user_downloader: downloader
    nexus_repo: word-cloud-build
    nexus_version: ''
    nexus_admin_password: admin
    nexus_config_maven: false
    nexus_delete_default_repos: true
    nexus_config_raw: true
    nexus_repos_raw_hosted:
    - name: "{{ nexus_repo }}"
      version_policy: release
      write_policy: allow
    nexus_roles:
    - id: nx-{{ nexus_user_uploader }}
      name: nx-{{ nexus_user_uploader }}
      description: uploader
      privileges:
      - nx-repository-view-raw-{{ nexus_repo }}-*
      roles: []
    - id: nx-{{ nexus_user_downloader }}
      name: nx-{{ nexus_user_downloader }}
      description: downloader
      privileges:
      - nx-repository-view-raw-{{ nexus_repo }}-read
      roles: []
    nexus_local_users:
    - username: "{{ nexus_user_uploader }}"
      state: present
      first_name: "{{ nexus_user_uploader }}"
      last_name: loader
      email: support@company.com
      password: "{{ nexus_user_uploader }}"
      roles:
      - nx-{{ nexus_user_uploader }}
    - username: "{{ nexus_user_downloader }}"
      state: present
      first_name: "{{ nexus_user_downloader }}"
      last_name: downloader
      email: support@company.com
      password: "{{ nexus_user_downloader }}"
      roles:
      - nx-{{ nexus_user_downloader }}

  roles:
    - role: ansible-thoteam.nexus3-oss
