---
- name: add Jenkins key
  apt_key:
    url: "https://pkg.jenkins.io/debian-stable/jenkins.io.key"
    state: present

- name: add Jenkins repository
  apt_repository:
    repo: 'deb https://pkg.jenkins.io/debian-stable binary/'
    state: present

- name: install packeges all other
  apt:
    pkg:
    - git
    - build-essential
    - default-jre
    - jq
    state: present
    update_cache: true

- name: install Jeninks
  apt:
    name: jenkins
    state: present
    update_cache: true

- name: wizard off
  lineinfile:
    dest: /etc/default/jenkins
    regexp: '^JAVA_ARGS='
    line: 'JAVA_ARGS="-Djenkins.install.runSetupWizard=false -Dhudson.security.csrf.DefaultCrumbIssuer.EXCLUDE_SESSION_ID=true -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8"'

- name: Jenkins is restarted
  service:
    name: jenkins
    state: restarted
    enabled: yes
  changed_when: false

- name: pause for 2 minutes
  pause:
    minutes: 2

- name: Copy admin_user
  copy:
    src: users/
    dest: /var/lib/jenkins/users
    owner: jenkins
    group: jenkins

- name: Copy templates
  copy:
    src: /templates/
    dest: /var/lib/jenkins/
    owner: jenkins
    group: jenkins

- name: remove file
  file:
    path: /var/lib/jenkins/identity.key.enc
    state: absent

- name: restart jenkins
  service:
    name: jenkins
    state: restarted
