Vagrant.configure("2") do |config|

  config.vm.box = "generic/debian11"
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disable = false

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2024
    vb.cpus   = 2
  end

#  config.vm.provision "shell", inline: <<-SHELL
#    sed -i "s/^PasswordAuthentication no\$/PasswordAuthentication yes/g" /etc/ssh/sshd_config
#    service sshd restart
#SHELL

  config.vm.define "jenkins.vm", primary: true do |jenkins|
    jenkins.vm.network "private_network", ip: "192.168.55.5"

  jenkins.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.galaxy_role_file = "inventory/requirements.yml"
    ansible.galaxy_roles_path = "/usr/share/ansible/collections"
    ansible.galaxy_command = "sudo ansible-galaxy collection install -r%{role_file} -p%{roles_path} --force"
    ansible.inventory_path = "inventory/hosts"
    ansible.become = true
    ansible.limit = "all"
  end

end


end
