---
#all
- name: add puppet repo to all
  hosts: all
  become: true
  tasks:

    - name: add repo
      yum:
        name: https://yum.puppet.com/puppet7-release-el-8.noarch.rpm
        disable_gpg_check: yes

#master deploy
- name: make puppet server
  hosts: master
  become: true
  tasks:

    - name: stop firewalld
      service:
        name: firewalld
        state: stopped
        enabled: false

    - name: install puppetserver and git
      yum:
        pkg:
          - puppetserver
          - git
        state: present

    - name: Export PATH
      lineinfile:
        dest: /etc/environment
        line: "PATH=/home/vagrant/.local/bin:/home/vagrant/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin:/opt/puppetlabs/puppet/bin"

    - name: install code management tool - r10k
      shell: /opt/puppetlabs/puppet/bin/gem install r10k

    - name: mkdir r10k
      file:
        path: /etc/puppetlabs/r10k
        state: directory
        mode: '0775'

    - name: create config file r10k.yaml
      file:
        path: /etc/puppetlabs/r10k/r10k.yaml
        state: touch

    - name: set config r10k
      blockinfile:
        path: /etc/puppetlabs/r10k/r10k.yaml
        block: |
          ---
          :cachedir: '/var/cache/r10k'
          :sources:
            :my-org:
              remote: 'https://github.com/vechugres/puppet.git'
              basedir: '/etc/puppetlabs/code/environments'

    - name: schedule r10k
      cron:
        name: "r10k"
        minute: "*/2"
        job: "/opt/puppetlabs/puppet/bin/r10k deploy environment -p"

    - name: set ram
      lineinfile:
        path: /etc/sysconfig/puppetserver
        regexp: '^JAVA_ARGS='
        insertbefore: '^JAVA_ARGS='
        line: 'JAVA_ARGS="-Xms256m -Xmx256m -Djrubby.logger.class-com.pupetlabs.jruby_utils.jruby.Slf4jLogger"'
        state: present

    - name: dns
      lineinfile:
        path: /etc/hosts
        line: "{{item}}"
      with_items:
        - '192.168.55.5 master.puppet'
        - '192.168.55.10 slave1.puppet'
        - '192.168.55.15 slave2.puppet'
        - '192.168.55.20 minecraft.puppet'

    - name: set master.puppet agent
      ini_file:
        path: /etc/puppetlabs/puppet/puppet.conf
        section: "{{ item.sect }}"
        option: "{{ item.option }}"
        value: "{{ item.value }}"
      with_items:
        - { sect: "server", option: "autosign", value: "true" }
        - { sect: "agent", option: "server", value: "master.puppet" }
        - { sect: "agent", option: "runinterval", value: "1m" }


    - name: enabled puppetserver
      service:
        name: puppetserver
        state: started
        enabled: true

    - name: enable puppet service on master
      service:
        name: puppet
        enabled: true
        state: started


#slaves deploy
- name: make puppet clients
  hosts: slaves
  become: true
  tasks:

    - name: install puppet agent
      yum:
        pkg: puppet-agent
        state: present

    - name: add puppet server dns
      lineinfile:
        path: /etc/hosts
        line: '192.168.55.5 master.puppet'

    - name: set puppet agent
      lineinfile:
        path: /etc/puppetlabs/puppet/puppet.conf
        line: "{{item}}"
      with_items:
        - '[agent]'
        - server = master.puppet
        - runinterval = 1m

    - name: enable puppet service on slaves
      service:
        name: puppet
        enabled: true
        state: started
