---

- hosts: all
  become: true
  tasks:

   - name: pp repo
     yum:
      name: https://yum.puppet.com/puppet7-release-el-8.noarch.rpm
      disable_gpg_check: yes

   - name: disable firewall
     service:
      name: firewalld
      state: stopped
      enabled: false
