---
#all
- hosts: all
  become: true
  tasks:

   - name: pp repo
     yum:
      name: https://yum.puppet.com/puppet7-release-el-8.noarch.rpm
      disable_gpg_check: yes

   - name: disable firewall
     service:
      name: firewalld
      state: stopped
      enabled: false

#master deploy
- hosts: master
  become: true
  tasks:

    - name: inst pp_srv
      yum:
        name:
        - puppetserver
        - git
        - nano
        state: latest

    - name: enable pp_srv daemon
      systemd:
       name: puppetserver
       enabled: yes
       state: started

    - name: start pp_srv daemon
      systemd:
       state: started
       name: puppetserver

    - name: less ram
      become: yes
      replace:
        path: /etc/sysconfig/puppetserver
        regexp: 'JAVA_ARGS="-Xms2g -Xmx2g'
        replace: 'JAVA_ARGS="-Xms256m -Xmx256m'

    - name: inst r10k
      shell: /opt/puppetlabs/puppet/bin/gem install r10k

    - name: conf dir r10k
      file:
        path: /etc/puppetlabs/r10k
        state: directory

    - name: conf r10k
      file:
        path: /etc/puppetlabs/r10k/r10k.yaml
        state: touch

    - name: Set config r10k
      blockinfile:
        path: /etc/puppetlabs/r10k/r10k.yaml
        block: |
          ---
          :cachedir: '/var/cache/r10k'
          :sources:
            :my-org:
            remote: 'git@github.com:vechugres/puppet.git'
            basedir: '/etc/puppetlabs/code/environments'

    - name: dns
      lineinfile:
       path: /etc/hosts
       line: "{{item}}"
      with_items:
       - '192.168.55.5 master.puppet'
       - '192.168.55.10 slave1.puppet'
       - '192.168.55.15 slave2.puppet'

    - name: add master.puppet
      lineinfile:
       path: /etc/puppetlabs/puppet/puppet.conf
       line: "{{item}}"
      with_items:
       - server = master.puppet
       - autosign = true

#slaves deploy
- hosts: slaves
  become: true
  tasks:

    - name: add pp_srv
      lineinfile:
        path: /etc/hosts
        line: '192.168.33.100 master.puppet puppet'

    - name: inst pp_ag
      yum:
       pkg: puppet-agent
       state: present

    - name: conf file
      lineinfile:
       path: /etc/puppetlabs/puppet/puppet.conf
       line: "{{item}}"
      with_items:
       - '[agent]'
       - 'server = master.puppet'
       - 'runinterval = 1m'

    - name: enable pp_srv daemon
      systemd:
       name: puppet
       enabled: yes
       state: started

    - name: restart pp_daemon
      systemd:
       state: restarted
       daemon_reload: yes
       name: puppet
