Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos8"

  config.ssh.insert_key = false

  config.vm.synced_folder ".", "/vagrant", disable = false

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 512
    vb.cpus   = 1
  end

  config.vm.define "slave1.puppet" do |slave|
    slave.vm.network "private_network", ip: "192.168.50.10"
    slave.vm.network "forwarded_port", guest: 80, host: 8080
    slave.vm.hostname = "slave1.puppet"

  end

  config.vm.define "slave2.puppet" do |slave|
    slave.vm.network "private_network", ip: "192.168.50.15"
    slave.vm.network "forwarded_port", guest: 81, host: 8081
    slave.vm.hostname = "slave2.puppet"

  end

  config.vm.define "master.puppet", primary: true do |master|
    master.vm.network "private_network", ip: "192.168.50.5"
    master.vm.hostname = "master.puppet"

    master.vm.provider("virtualbox") { |vb| vb.memory = 1024 }

    master.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "Playbook.yml"
      ansible.become = true

    end

  end

end
