# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "vechugres-centos8"

  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 81, host: 8081, host_ip: "127.0.0.1"

  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant"


  config.vm.provision "shell", inline: <<-SHELL
	#apt update
	#sudo apt install -y apache2
  #sudo apt install -y libapache2-mod-php php php-cli php-mysql php-json php-opcache php-mbstring php-intl php-xml php-gd php-zip php-curl php-xmlrpc unzip
	sudo setsebool -P httpd_unified 1
  #static
  sudo mkdir -p /var/www/static/html
  sudo chown -R root:vagrant /var/www/static/html
	sudo chmod -R 755 /var/www
	sudo cp /vagrant/index.html /var/www/static/html
	#sudo cp /vagrant/static.conf /etc/apache2/sites-available/
  #sudo a2ensite static.conf
  
  #dynamic
  sudo mkdir -p /var/www/dynamic/html
  sudo chown -R root:vagrant /var/www/dynamic/html
  sudo chmod -R 755 /var/www
  sudo cp /vagrant/index.php /var/www/dynamic/html
  #sudo chcon -R --type=httpd_sys_rw_content_t /var/www/dynamic/html
  #sudo cp /vagrant/dynamic.conf /etc/apache2/sites-available/
  #sudo a2ensite dynamic.conf
  #sudo cp /vagrant/ports.conf /etc/apache2/
  #sudo a2dissite 000-default.conf

  sudo mkdir /etc/httpd/sites-available
	sudo mkdir /etc/httpd/sites-enabled

  sudo cp /vagrant/static.conf /etc/httpd/sites-available/
	sudo cp /vagrant/dynamic.conf /etc/httpd/sites-available/
  sudo cp /vagrant/httpd.conf /etc/httpd/conf/

  sudo ln -s /etc/httpd/sites-available/static.conf /etc/httpd/sites-enabled/static.conf
	sudo ln -s /etc/httpd/sites-available/dynamic.conf /etc/httpd/sites-enabled/dynamic.conf

  
  sudo systemctl start httpd
  SHELL

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.


  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
