apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-site
spec:
  selector:
    matchLabels:
      app: static
  replicas: 3
  template:
    metadata:
      labels:
        app: static
    spec:
      containers:
      - name: static
        image: vechugres/static:latest
        ports:
        - containerPort: 80
        readinessProbe:
          initialDelaySeconds: 15
          timeoutSeconds: 5
          httpGet:
            path: /
            port: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
  name: service-static
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 32000
  selector:
    app: static
