version: '3'
services:

  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    ports:
      - 80:8080
    networks:
      - alina
    container_name: jenkins
    volumes:
      - /var/run/docker.sock:/jenkins/workspace
  nexus:
    build:
      context: ./nexus
      dockerfile: Dockerfile
    ports:
      - 81:8081
    networks:
      - alina
    container_name: nexus
networks:
  alina:
    name: alina
volumes:
