---
- name: Install plugins
  jenkins_plugin:
    name: "{{ item }}"
    state: present
    timeout: 300
    with_dependencies: yes
    url_username: "{{ jenkins_user }}"
    url_password: "{{ jenkins_password }}"
  register: plugin_results
  until: plugin_results is success
  retries: 5
  delay: 10
  loop:
  - credentials-binding
  - credentials
  - plain-credentials
  - git
  - github
  - github-branch-source
  - golang
  - pipeline
  - pipeline-stage-view
  - pipeline-github-lib
  - workflow-cps
  - workflow-aggregator
  - workflow-durable-task-step
  - pipeline-utility-steps
  - pipeline-stage-view
  - ssh-steps
  - pipeline-stage-step
  - github-branch-source
  - ssh
  - ssh-credentials
  - sshd
  - ssh-slaves
  - nexus-artifact-uploader
  - timestamper
  - docker-workflow

#- name: restart jenkins
#  service:
#    name: jenkins
#    state: restarted
